apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      serviceAccountName: monitor-sa
      containers:
      - name: monitor
        image: ghcr.io/qweeah/ratify/monitor:demo
        imagePullPolicy: Always
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
      volumes:
      - name: shared-data
        hostPath:
          path: /var/shared-data